import {  Category, Product } from "../types/index";
export const  products: Product[] = [
  {
    id: "1",
    title: "iPhone 15",
    description: "Latest Apple smartphone",
    price: 80000,
    image: "/images/iPhone_15_Pink.jpg",
    category: "electronics",
    rating: 4.5,
    stock: 10,
    createdAt: "2025-01-01",
  },
  {
    id: "2",
    title: "Samsung Galaxy S24",
    description: "Flagship Android phone",
    price: 75000,
    image: "/images/samgal-24.jpg",
    category: "electronics",
    rating: 4.4,
    stock: 12,
    createdAt: "2025-01-05",
  },
  {
    id: "3",
    title: "Nike Shoes",
    description: "Comfort running shoes",
    price: 5000,
    image: "/images/niki2.jpg",
    category: "fashion",
    rating: 4.2,
    stock: 20,
    createdAt: "2025-01-10",
  },
  {
    id: "4",
    title: "Adidas Sneakers",
    description: "Stylish everyday wear",
    price: 4500,
    image: "/images/niki1.jpg",
    category: "fashion",
    rating: 4.1,
    stock: 18,
    createdAt: "2025-01-12",
  },
  {
    id: "5",
    title: "Sony Headphones",
    description: "Noise cancelling headphones",
    price: 6000,
    image: "/images/sony.jpg",
    category: "electronics",
    rating: 4.6,
    stock: 15,
    createdAt: "2025-01-15",
  },
  {
    id: "6",
    title: "Dell Laptop",
    description: "High performance laptop",
    price: 90000,
    image: "/images/laprtop.jpg",
    category: "electronics",
    rating: 4.5,
    stock: 8,
    createdAt: "2025-01-18",
  },
  {
    id: "7",
    title: "One Plus",
    description: "Latest mobile phone",
    price: 50000,
    image: "/images/One-Plus.jpg",
    category: "electronics",
    rating: 4.2,
    stock: 20,
    createdAt: "2025-02-10",
  },
  {
    id: "8",
    title: "Boat Headphones",
    description: "Noise cancelling headphones",
    price: 3000,
    image: "/images/headphones.jpg",
    category: "electronics",
    rating: 4.3,
    stock: 15,
    createdAt: "2025-03-15",
  },
  {
    id: "9",
    title: "Puma T-Shirt",
    description: "Casual wear t-shirt",
    price: 1200,
    image: "/images/shirtmen.jpg",
    category: "fashion",
    rating: 4.0,
    stock: 25,
    createdAt: "2025-02-01",
  },
  {
    id: "10",
    title: "Levi's Jeans",
    description: "Denim jeans",
    price: 2500,
    image: "/images/pant1.jpg",
    category: "fashion",
    rating: 4.3,
    stock: 30,
    createdAt: "2025-02-03",
  },
  {
    id: "11",
    title: "Apple Watch",
    description: "Smart fitness watch",
    price: 30000,
    image: "/images/watch.jpg",
    category: "electronics",
    rating: 4.6,
    stock: 10,
    createdAt: "2025-02-05",
  },
  {
    id: "12",
    title: "Mi Band",
    description: "Affordable fitness tracker",
    price: 2500,
    image: "/images/watch1.jpg",
    category: "electronics",
    rating: 4.2,
    stock: 22,
    createdAt: "2025-02-07",
  },
  {
    id: "13",
    title: "Formal Shirt",
    description: "Office wear shirt",
    price: 1800,
    image: "/images/shirt.jpg",
    category: "fashion",
    rating: 4.1,
    stock: 18,
    createdAt: "2025-02-09",
  },
  {
    id: "14",
    title: "Jacket",
    description: "Winter jacket",
    price: 3500,
    image: "/images/jacket.jpg",
    category: "fashion",
    rating: 4.4,
    stock: 12,
    createdAt: "2025-02-11",
  },
  {
    id: "15",
    title: "Bluetooth Speaker",
    description: "Portable speaker",
    price: 2200,
    image: "/images/jbl.jpg",
    category: "electronics",
    rating: 4.3,
    stock: 20,
    createdAt: "2025-02-13",
  },
  {
    id: "16",
    title: "Tablet",
    description: "Android tablet",
    price: 20000,
    image: "/images/tab.jpg",
    category: "electronics",
    rating: 4.2,
    stock: 14,
    createdAt: "2025-02-15",
  },
  {
    id: "17",
    title: "Cap",
    description: "Stylish cap",
    price: 500,
    image: "/images/cap.jpg",
    category: "fashion",
    rating: 3.9,
    stock: 40,
    createdAt: "2025-02-17",
  },
  {
    id: "18",
    title: "Backpack",
    description: "Travel backpack",
    price: 1500,
    image: "/images/bag.jpg",
    category: "fashion",
    rating: 4.2,
    stock: 28,
    createdAt: "2025-02-19",
  },
  {
    id: "19",
    title: "Gaming Mouse",
    description: "High precision mouse",
    price: 1200,
    image: "/images/mouse.jpg",
    category: "electronics",
    rating: 4.5,
    stock: 25,
    createdAt: "2025-02-21",
  },
  {
    id: "20",
    title: "Keyboard",
    description: "Mechanical keyboard",
    price: 3500,
    image: "/images/keyboard.jpg",
    category: "electronics",
    rating: 4.6,
    stock: 16,
    createdAt: "2025-02-25",
  },
];

export const getCategories = (): Category[] => {
  const map: Record<string, Product[]> = {};

  products.forEach((product) => {
    if (!map[product.category]) {
      map[product.category] = [];
    }

    map[product.category].push(product);
  });

  return Object.keys(map).map((key) => ({
    name: key,
    products: map[key],
  }));
};

export const getProductById = (id: string) => {
  return products.find((p) => p.id === id);
};